blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path("", views.index, name="index"),
    path('<slug:post>/', views.post_single, name="post_single"),
    path("category/<category>/", views.CatListView.as_view(), name="category"),
]

my_django_app/urls.py
"""my_django_app URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.1/topics/http/urls/
"""
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('travello/', include('travello.urls')),
    path('', include('blog.urls', namespace='blog')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    # path('polls/', include('polls.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from mptt.models import MPTTModel, TreeForeignKey


def user_directory_path(instance, filename):
    return 'blog/posts/{0}/{1}'.format(instance.id, filename)


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):

    class NewManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status='published')

    options = [
        ('draft', 'Draft'),
        ('published', 'Published'),
    ]
    title = models.CharField(max_length=250)
    image = models.ImageField(upload_to=user_directory_path,
                              default='blog/posts/default.png')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    slug = models.SlugField(max_length=250, unique_for_date='publish_date')
    publish_date = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    content = models.TextField()
    status = models.CharField(max_length=10, choices=options, default='draft')
    votes = models.IntegerField(default=0)

    objects = models.Manager()
    newmanager = NewManager()

    class Meta:
        ordering = ('-publish_date',)

    def __str__(self):
        return self.title


class Comment(MPTTModel):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name="children")
    name = models.CharField(max_length=50)
    email = models.EmailField()
    content = models.TextField()
    publish = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=True)

    class Meta:
        ordering = ('publish',)

    def __str__(self):
        return f"Comment by {self.name}"

blog/forms.py
from django import forms
from .models import Comment
from mptt.forms import TreeNodeChoiceField


class NewCommentForm(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comment.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['parent'].widget.attrs.update({'class': 'd-none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comment
        fields = ('name', 'parent', 'email', 'content')
        widget = {
            "name": forms.TextInput(attrs={"class": "col-sm-12"}),
            "email": forms.TextInput(attrs={"class": "col-sm-12"}),
            "content": forms.Textarea(attrs={"class": "form-control"}),
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from django.http import HttpResponse
from .forms import NewCommentForm
from .models import Post, Comment, Category
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    all_posts = Post.newmanager.all()

    return render(request, 'blog/index.html', {'posts': all_posts})


def post_single(request, post):

    post = get_object_or_404(Post, slug=post, status='published')

    allcomments = post.comments.filter(status=True)
    page = request.GET.get('page', 1)
    paginator = Paginator(allcomments, 6)

    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    user_comment = None

    if request.method == 'POST':
        comment_form = NewCommentForm(request.POST)
        if comment_form.is_valid():
            user_comment = comment_form.save(commit=False)
            user_comment.post = post
            user_comment.save()
            return HttpResponseRedirect('/'+post.slug)

    else:
        comment_form = NewCommentForm()
    return render(
        request,
        'blog/single.html',
        {
            'post': post,
            'comments': user_comment,
            'comments': comments,
            'comment_form': comment_form,
            'allcomments': allcomments,
        },
    )


class CatListView(ListView):
    template_name = 'blog/category.html'
    context_object_name = 'catlist'

    def get_queryset(self):
        content = {
            'cat': self.kwargs['category'],
            'posts': Post.objects.filter(category__name=self.kwargs['category']).filter(status='published')
        }
        return content


def category_list(request):
    category_list = Category.objects.exclude(name="default")
    context = {
        "category_list": category_list,
    }
    return context

templates/blog/category.html
{% extends "../base/base.html" %}
{% block title%}
Catlist
{% endblock %}
{% block content %}
<div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
        <div class="col-12 pb-5"><h1>List of {{catlist.cat}} posts</h1></div>
        {% for post in catlist.posts %}
            <div class="col-md-4">
            <a class="text-dark" href="#">
                <div class="card mb-4 box-shadow">
                    <img class="card-img-top" src="{{post.image.url}}" alt="{{post.title}}">
                    <div class="card-body">
                    <h2 style="font-size:18px;font-weight:bold">{{post.title|truncatechars:50}}</h2>
                    <p class="card-text">{{post.content|truncatechars:50}}...</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                            <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                        </div>
                        <small class="text-muted">9 mins</small>
                    </div>
                    </div>
                </div>
            </a>
            </div>
            {%endfor%}
    </div>
</div>
  
{% endblock%}

templates/blog/single.html
{% extends "../base/base.html" %}
      
{% block title %}
{{post.title}}
{% endblock %}

{% block content %}
<style>
{% comment %} .children form{
    margin-left:-48px;
}
.children .children form{
    margin-left:-96px;
} {% endcomment %}
</style>
<div class="container">
    <div class="row justify-content-md-center pt-5">
        <div class="col-md-8">
            <img clas="img-fluid" src="{{post.image.url}}" alt="{{post.title}}">
            <div class="col-12"><h1>{{post.title}}</h1></div>
            <div class="col-12"><p>{{post.content|safe}}</p></div>
        </div>

        <div class="col-md-8">
            {% with allcomments.count as total_comments%}
            <h2>
                {{total_comments}} comment{{total_comments|pluralize}} 
            </h2>
            {% endwith %}

            {% load mptt_tags %}
            <div>
                {% recursetree comments%}
                <div id={{node.id}} class="my-2 p-2" style="border:1px solid grey">
                    <div class="d-flex justify-content-between">BY {{node.name}}<div>{{node.publish}}</div>
                    </div>
                    <div id="{{ node.id }}" style="font-weight:750">{{node.content}}</div>
                    </hr>
                    {% if node.level < 3 %}
                        <button class="button" onclick="myFunction({{node.id}})">Reply</button>
                    {% endif %}
                </div>
                    {% if not node.is_leaf_node %}
                        <div class="children pl-2 pl-md-5">
                            {{ children }}
                        </div>
                    {%endif%}
                {% endrecursetree %}
            </div>
            <div class="py-4">
                <nav aria-label="Page navigation example">
                    {% if comments.has_other_pages %}
                    <ul class="pagination">
                        {% if comments.has_previous %}
                            <li class="page-item"><a class="page-link" href="?page={{comments.previous_page_number}}">Previous</a></li>
                        {% else %}
                            <li class="page-item-disabled"><a class="page-link" href="#"/>Previous</a></li>
                        {% endif %}
                        {% for i in comments.paginator.page_range %}
                            {% if comments.number == i %}
                                <li class="page-item active"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>  
                            {%else%}
                                <li class="page-item"><a class="page-link" href="?page={{i}}"/>{{i}}</a></li>
                            {%endif%}
                        {%endfor%}
                        {% if comments.has_next %}
                            <li class="page-item"><a class="page-link" href="?page={{comments.next_page_number}}">Next</a></li>
                        {% else %}
                            <li class="page-item-disabled"><a class="page-link" href="#"/>Next</a></li>
                        {% endif %}
                    </ul>
                    {%endif%}
                </nav>
            </div>
            <h2>Make a Comment</h2>
            <form id="myForm" method="POST">
                {{comment_form.as_p}}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary btn-lg btn-block">Submit</button>
            </form>
        </div>
    </div>
</div>
<script>
    function myFunction(id){
        if(document.contains(document.getElementById('newForm'))){
            document.getElementById("newForm").remove();
        }
        var a=document.getElementById(id);
        a.insertAdjacentHTML('beforeend',
            `<form id="newForm" class="form-insert py-2" method="POST">\
            <div class="d-flex justify-content-between"><h2>Reply:</h2><button class="btn" onclick="exitForm()" >Close</button></div>\
            <p><label for="id_name">Name:</label>\ 
            <input type="text" name="name" maxlength="50" required="" id="id_name"></p>\
            <p> <select name="parent" class="d-none" id="id_parentt">\
            <option value="` + id + `" selected="` + id + `"></option>\
            </select></p>\
            <p><label for="id_email">Email:</label>\ 
            <input type="email" name="email" maxlength="254" required="" id="id_email"></p>\
            <p><label for="id_content">Content:</label>\
            <textarea name="content" cols="40" rows="10" required="" id="id_content"></textarea></p>\
            {% csrf_token %}\
            <button type="submit" class="btn btn-primary btn-lg btn-block">Reply</button> \
            </form>`);

    }
    function exitForm(){
        document.getElementById("newForm").remove();
    }


    $('#myForm').trigger("reset")
</script>

{% endblock%}

